// Порядок полей data dictionary v1 (§16): сгруппированные строки таблицы
// разворачиваются в плоский список с сохранением порядка строк и порядка полей
// внутри строки. Этот же список — фиксированный CSV-header (§16: «первая
// строка — фиксированный header в порядке полей data dictionary»).

import type { ExportRecordBase } from '@fluxradar/contracts';

export const EXPORT_RECORD_FIELDS = [
  'schema_version',
  'record_type',
  'scan_id',
  'domain',
  'plan',
  'started_at',
  'completed_at',
  'observed_at',
  'ruleset_version',
  'module',
  'module_status',
  'scan_status',
  'request_id_source',
  'usage_source',
  'tokenizer_version',
  'coverage',
  'applicable_checks',
  'completed_applicable_checks',
  'score',
  'applicable_targets',
  'affected_targets',
  'rule_penalty',
  'score_delta',
  'issue_id',
  'fingerprint',
  'rule_id',
  'target_kind',
  'normalized_url',
  'normalized_resource',
  'normalized_selector',
  'normalized_parameter',
  'rule_variant',
  'metric_key',
  'evidence_group_id',
  'category',
  'severity',
  'confidence',
  'status',
  'target_url',
  'evidence_type',
  'evidence_ref',
  'evidence_excerpt',
  'recommendation',
  'status_reason',
  'provider',
  'api_version',
  'model_id',
  'prompt_version',
  'request_id',
  'ai_request_key',
  'raw_text',
  'provider_created_at',
  'finish_reason',
  'citations',
  'usage',
  'deletion_evidence_ref',
] as const satisfies readonly (keyof ExportRecordBase)[];

export type ExportRecordField = (typeof EXPORT_RECORD_FIELDS)[number];
