// JSON Schema `fluxradar-export-1.0-record.schema.json` — дословная копия из
// FluxRadar-Feature-Plan.md §16 («Машинный контракт»). Схему НЕ переписывать
// и не «улучшать»: расхождения буквы схемы и удобства кода решаются в пользу
// схемы; любое изменение требует новой schema_version (§16).

export const EXPORT_RECORD_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://fluxradar.com/schemas/export/1.0/record.schema.json',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema_version',
    'record_type',
    'scan_id',
    'domain',
    'plan',
    'started_at',
    'completed_at',
    'observed_at',
    'ruleset_version',
    'module_status',
    'scan_status',
  ],
  allOf: [
    {
      if: {
        properties: {
          record_type: { const: 'module' },
          module_status: { enum: ['Partial', 'Unavailable', 'Not applicable'] },
        },
      },
      then: {
        required: ['status_reason'],
        properties: { status_reason: { type: 'string', minLength: 1 } },
      },
    },
    {
      if: {
        properties: {
          record_type: { const: 'ai_response' },
          module_status: { const: 'Partial' },
        },
      },
      then: {
        required: ['status_reason'],
        properties: { status_reason: { type: 'string', minLength: 1 } },
      },
    },
    {
      if: {
        properties: {
          record_type: { const: 'summary' },
          scan_status: { enum: ['Partial', 'Failed', 'Cancelled'] },
        },
      },
      then: {
        required: ['status_reason'],
        properties: { status_reason: { type: 'string', minLength: 1 } },
      },
    },
    {
      if: {
        properties: {
          record_type: { const: 'summary' },
          scan_status: { const: 'Completed' },
        },
      },
      then: {
        properties: { status_reason: { const: null } },
      },
    },
    {
      if: {
        properties: {
          record_type: { enum: ['module', 'ai_response'] },
          module_status: { const: 'Completed' },
        },
      },
      then: {
        properties: { status_reason: { const: null } },
      },
    },
  ],
  oneOf: [
    {
      title: 'summary record',
      required: [
        'record_type',
        'module',
        'coverage',
        'score',
        'issue_id',
        'fingerprint',
        'category',
        'severity',
        'confidence',
        'status',
        'target_url',
        'evidence_type',
        'evidence_ref',
        'recommendation',
        'status_reason',
      ],
      properties: {
        record_type: { const: 'summary' },
        module: { const: null },
        module_status: { const: null },
        scan_status: { enum: ['Partial', 'Completed', 'Failed', 'Cancelled'] },
        coverage: { type: 'number', minimum: 0, maximum: 1 },
        applicable_checks: { const: null },
        completed_applicable_checks: { const: null },
        issue_id: { const: null },
        fingerprint: { const: null },
        category: { const: null },
        severity: { const: null },
        confidence: { const: null },
        status: { const: null },
        target_url: { const: null },
        evidence_type: { const: null },
        evidence_ref: { const: null },
        recommendation: { const: null },
        evidence_excerpt: { const: null },
        status_reason: { type: ['string', 'null'] },
        rule_id: { const: null },
        target_kind: { const: null },
        normalized_url: { const: null },
        normalized_resource: { const: null },
        normalized_selector: { const: null },
        normalized_parameter: { const: null },
        rule_variant: { const: null },
        metric_key: { const: null },
        evidence_group_id: { const: null },
        request_id_source: { const: null },
        usage_source: { const: null },
        tokenizer_version: { const: null },
        provider: { const: null },
        api_version: { const: null },
        model_id: { const: null },
        prompt_version: { const: null },
        request_id: { const: null },
        ai_request_key: { const: null },
        raw_text: { const: null },
        provider_created_at: { const: null },
        citations: { const: null },
        usage: { const: null },
        finish_reason: { const: null },
        deletion_evidence_ref: { const: null },
        applicable_targets: { const: null },
        affected_targets: { const: null },
        rule_penalty: { const: null },
        score_delta: { const: null },
      },
    },
    {
      title: 'module record',
      required: [
        'record_type',
        'module',
        'module_status',
        'coverage',
        'applicable_checks',
        'completed_applicable_checks',
        'score',
        'issue_id',
        'fingerprint',
        'category',
        'severity',
        'confidence',
        'status',
        'target_url',
        'evidence_type',
        'evidence_ref',
        'recommendation',
        'status_reason',
      ],
      properties: {
        record_type: { const: 'module' },
        module: { type: 'string', minLength: 1 },
        module_status: { enum: ['Completed', 'Partial', 'Unavailable', 'Not applicable'] },
        scan_status: { const: null },
        coverage: { type: 'number', minimum: 0, maximum: 1 },
        applicable_checks: { type: 'integer', minimum: 0 },
        completed_applicable_checks: { type: 'integer', minimum: 0 },
        issue_id: { const: null },
        fingerprint: { const: null },
        category: { const: null },
        severity: { const: null },
        confidence: { const: null },
        status: { const: null },
        target_url: { const: null },
        evidence_type: { const: null },
        evidence_ref: { const: null },
        recommendation: { const: null },
        evidence_excerpt: { const: null },
        status_reason: { type: ['string', 'null'] },
        rule_id: { const: null },
        target_kind: { const: null },
        normalized_url: { const: null },
        normalized_resource: { const: null },
        normalized_selector: { const: null },
        normalized_parameter: { const: null },
        rule_variant: { const: null },
        metric_key: { const: null },
        evidence_group_id: { const: null },
        request_id_source: { const: null },
        usage_source: { const: null },
        tokenizer_version: { const: null },
        provider: { const: null },
        api_version: { const: null },
        model_id: { const: null },
        prompt_version: { const: null },
        request_id: { const: null },
        ai_request_key: { const: null },
        raw_text: { const: null },
        provider_created_at: { const: null },
        citations: { const: null },
        usage: { const: null },
        finish_reason: { const: null },
        deletion_evidence_ref: { const: null },
        applicable_targets: { const: null },
        affected_targets: { const: null },
        rule_penalty: { const: null },
        score_delta: { const: null },
      },
    },
    {
      title: 'ai_response record',
      required: [
        'record_type',
        'module',
        'module_status',
        'scan_status',
        'coverage',
        'score',
        'applicable_targets',
        'affected_targets',
        'rule_penalty',
        'score_delta',
        'issue_id',
        'fingerprint',
        'category',
        'severity',
        'confidence',
        'status',
        'target_url',
        'evidence_type',
        'evidence_ref',
        'evidence_excerpt',
        'recommendation',
        'status_reason',
        'provider',
        'api_version',
        'model_id',
        'prompt_version',
        'request_id',
        'ai_request_key',
        'request_id_source',
        'usage_source',
        'raw_text',
        'provider_created_at',
        'citations',
        'usage',
        'finish_reason',
        'deletion_evidence_ref',
      ],
      properties: {
        record_type: { const: 'ai_response' },
        module: { const: 'AI SEO / GEO' },
        module_status: { enum: ['Completed', 'Partial'] },
        scan_status: { const: null },
        coverage: { const: null },
        applicable_checks: { const: null },
        completed_applicable_checks: { const: null },
        score: { const: null },
        applicable_targets: { const: null },
        affected_targets: { const: null },
        rule_penalty: { const: null },
        score_delta: { const: null },
        issue_id: { const: null },
        fingerprint: { const: null },
        category: { const: null },
        severity: { const: null },
        confidence: { const: null },
        status: { const: null },
        target_url: { const: null },
        evidence_type: { const: null },
        evidence_ref: { const: null },
        evidence_excerpt: { const: null },
        recommendation: { const: null },
        status_reason: { type: ['string', 'null'] },
        rule_id: { const: null },
        target_kind: { const: null },
        normalized_url: { const: null },
        normalized_resource: { const: null },
        normalized_selector: { const: null },
        normalized_parameter: { const: null },
        rule_variant: { const: null },
        metric_key: { const: null },
        evidence_group_id: { const: null },
        provider: { type: 'string', minLength: 1 },
        api_version: { type: 'string', minLength: 1 },
        model_id: { type: 'string', minLength: 1 },
        prompt_version: { type: 'string', minLength: 1 },
        request_id: { type: 'string', minLength: 1 },
        ai_request_key: { type: 'string', minLength: 1 },
        usage_source: { enum: ['provider', 'estimated'] },
        request_id_source: { enum: ['provider', 'local'] },
        raw_text: { type: 'string' },
        provider_created_at: { type: ['string', 'null'], format: 'date-time', pattern: 'Z$' },
        citations: { type: 'array', items: { type: 'string' } },
        usage: {
          type: 'object',
          additionalProperties: false,
          required: ['input_tokens', 'output_tokens', 'total_tokens'],
          properties: {
            input_tokens: { type: 'integer', minimum: 0 },
            output_tokens: { type: 'integer', minimum: 0 },
            total_tokens: { type: 'integer', minimum: 0 },
            reasoning_units: { type: ['integer', 'null'], minimum: 0 },
            search_units: { type: ['integer', 'null'], minimum: 0 },
            citation_units: { type: ['integer', 'null'], minimum: 0 },
          },
        },
        finish_reason: { enum: ['stop', 'length', 'safety', 'error', null] },
        deletion_evidence_ref: { type: 'string', minLength: 1 },
      },
    },
    {
      title: 'issue record',
      required: [
        'record_type',
        'module',
        'module_status',
        'coverage',
        'score',
        'applicable_targets',
        'affected_targets',
        'rule_penalty',
        'score_delta',
        'rule_id',
        'target_kind',
        'normalized_url',
        'normalized_resource',
        'normalized_selector',
        'normalized_parameter',
        'rule_variant',
        'metric_key',
        'evidence_group_id',
        'issue_id',
        'fingerprint',
        'category',
        'severity',
        'confidence',
        'status',
        'target_url',
        'evidence_type',
        'evidence_ref',
        'evidence_excerpt',
        'recommendation',
        'status_reason',
      ],
      properties: {
        record_type: { const: 'issue' },
        module: { type: 'string', minLength: 1 },
        module_status: { enum: ['Completed', 'Partial'] },
        scan_status: { const: null },
        coverage: { const: null },
        applicable_checks: { const: null },
        completed_applicable_checks: { const: null },
        score: { const: null },
        applicable_targets: { type: 'integer', minimum: 0 },
        affected_targets: { type: 'integer', minimum: 0 },
        rule_penalty: { type: 'number', minimum: 0, maximum: 25 },
        score_delta: { type: 'number', minimum: -25, maximum: 0 },
        rule_id: { type: 'string', minLength: 1 },
        target_kind: { enum: ['page', 'site', 'api', 'environment'] },
        normalized_url: { type: 'string' },
        normalized_resource: { type: 'string' },
        normalized_selector: { type: 'string' },
        normalized_parameter: { type: 'string' },
        rule_variant: { type: 'string', minLength: 1 },
        metric_key: { type: ['string', 'null'] },
        evidence_group_id: { type: ['string', 'null'] },
        issue_id: { type: 'string', minLength: 1 },
        fingerprint: { type: 'string', pattern: '^fluxradar-fp-v1:.+' },
        category: { type: 'string', minLength: 1 },
        severity: { enum: ['Critical', 'High', 'Medium', 'Low'] },
        confidence: { type: 'number', minimum: 0, maximum: 1 },
        status: { enum: ['New', 'Acknowledged', 'Resolved', 'Reopened', 'Ignored', 'False Positive'] },
        target_url: { type: 'string', format: 'uri' },
        evidence_type: { enum: ['none', 'http', 'dom', 'screenshot', 'trace', 'mixed'] },
        evidence_ref: { type: 'string', minLength: 1 },
        evidence_excerpt: { type: ['string', 'null'], maxLength: 2048 },
        recommendation: { type: 'string', minLength: 1 },
        status_reason: { const: null },
        request_id_source: { const: null },
        usage_source: { const: null },
        tokenizer_version: { const: null },
        provider: { const: null },
        api_version: { const: null },
        model_id: { const: null },
        prompt_version: { const: null },
        request_id: { const: null },
        ai_request_key: { const: null },
        raw_text: { const: null },
        provider_created_at: { const: null },
        citations: { const: null },
        usage: { const: null },
        finish_reason: { const: null },
        deletion_evidence_ref: { const: null },
      },
    },
  ],
  properties: {
    schema_version: { const: '1.0' },
    record_type: { enum: ['summary', 'module', 'ai_response', 'issue'] },
    scan_id: { type: 'string', minLength: 1 },
    domain: { type: 'string', format: 'uri' },
    plan: { const: 'Complete Scan' },
    started_at: { type: 'string', format: 'date-time', pattern: 'Z$' },
    completed_at: { type: 'string', format: 'date-time', pattern: 'Z$' },
    observed_at: { type: 'string', format: 'date-time', pattern: 'Z$' },
    ruleset_version: { type: 'string', minLength: 1 },
    module: {
      enum: [
        'SEO',
        'AI SEO / GEO',
        'Security',
        'Performance',
        'Accessibility',
        'Reliability',
        'Content Quality',
        'Privacy',
        'UX/Conversion',
        'Analytics',
        null,
      ],
    },
    module_status: { enum: [null, 'Completed', 'Partial', 'Unavailable', 'Not applicable'] },
    scan_status: { enum: [null, 'Partial', 'Completed', 'Failed', 'Cancelled'] },
    request_id_source: { enum: ['provider', 'local', null] },
    usage_source: { enum: ['provider', 'estimated', null] },
    tokenizer_version: { type: ['string', 'null'] },
    coverage: { type: ['number', 'null'], minimum: 0, maximum: 1 },
    applicable_checks: { type: ['integer', 'null'], minimum: 0 },
    completed_applicable_checks: { type: ['integer', 'null'], minimum: 0 },
    score: { type: ['number', 'null'], minimum: 0, maximum: 100 },
    applicable_targets: { type: ['integer', 'null'], minimum: 0 },
    affected_targets: { type: ['integer', 'null'], minimum: 0 },
    rule_penalty: { type: ['number', 'null'], minimum: 0, maximum: 25 },
    score_delta: { type: ['number', 'null'], minimum: -25, maximum: 0 },
    rule_id: { type: ['string', 'null'] },
    target_kind: { enum: ['page', 'site', 'api', 'environment', null] },
    normalized_url: { type: ['string', 'null'] },
    normalized_resource: { type: ['string', 'null'] },
    normalized_selector: { type: ['string', 'null'] },
    normalized_parameter: { type: ['string', 'null'] },
    rule_variant: { type: ['string', 'null'] },
    metric_key: { type: ['string', 'null'] },
    evidence_group_id: { type: ['string', 'null'] },
    issue_id: { type: ['string', 'null'] },
    fingerprint: { type: ['string', 'null'], pattern: '^fluxradar-fp-v1:' },
    category: { type: ['string', 'null'] },
    severity: { enum: ['Critical', 'High', 'Medium', 'Low', null] },
    confidence: { type: ['number', 'null'], minimum: 0, maximum: 1 },
    status: {
      enum: ['New', 'Acknowledged', 'Resolved', 'Reopened', 'Ignored', 'False Positive', null],
    },
    target_url: { type: ['string', 'null'], format: 'uri' },
    evidence_type: { enum: ['none', 'http', 'dom', 'screenshot', 'trace', 'mixed', null] },
    evidence_ref: { type: ['string', 'null'] },
    recommendation: { type: ['string', 'null'] },
    evidence_excerpt: { type: ['string', 'null'], maxLength: 2048 },
    status_reason: { type: ['string', 'null'] },
    provider: { type: ['string', 'null'] },
    api_version: { type: ['string', 'null'] },
    model_id: { type: ['string', 'null'] },
    prompt_version: { type: ['string', 'null'] },
    request_id: { type: ['string', 'null'] },
    ai_request_key: { type: ['string', 'null'] },
    raw_text: { type: ['string', 'null'] },
    provider_created_at: { type: ['string', 'null'], format: 'date-time', pattern: 'Z$' },
    citations: { type: ['array', 'null'], items: { type: 'string' } },
    usage: { type: ['object', 'null'] },
    finish_reason: { type: ['string', 'null'] },
    deletion_evidence_ref: { type: ['string', 'null'] },
  },
} as const;
