import type { RuleDescriptor } from './ruleset-types.js';

const SEO_TECHNICAL_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'SEO-TECH-001',
    module: 'SEO',
    title: 'robots.txt',
    category: 'technical',
    targetKind: 'site',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'GET /robots.txt: missing, unreachable, or unparseable file yields a finding',
  },
  {
    ruleId: 'SEO-TECH-002',
    module: 'SEO',
    title: 'sitemap.xml',
    category: 'technical',
    targetKind: 'site',
    severity: 'Low',
    scoring: 'scored',
    oracle: 'sitemap.xml missing, unreachable, or not valid XML yields a finding',
  },
  {
    ruleId: 'SEO-TECH-003',
    module: 'SEO',
    title: 'HTTP status',
    category: 'technical',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'final HTTP status of the in-scope page differs from 200',
  },
  {
    ruleId: 'SEO-TECH-004',
    module: 'SEO',
    title: 'canonical URL',
    category: 'technical',
    targetKind: 'page',
    severity: 'High',
    scoring: 'scored',
    oracle:
      'rel=canonical missing, duplicated, or pointing to a different URL than the page itself',
  },
  {
    ruleId: 'SEO-TECH-005',
    module: 'SEO',
    title: 'redirect chains/cycles',
    category: 'technical',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'redirect chain longer than one hop or a redirect cycle (crawler cap: 5 redirects)',
  },
  {
    ruleId: 'SEO-TECH-006',
    module: 'SEO',
    title: '4xx/5xx pages',
    category: 'technical',
    targetKind: 'page',
    severity: 'High',
    scoring: 'scored',
    oracle: 'in-scope page responds with a 4xx or 5xx status',
  },
  {
    ruleId: 'SEO-TECH-007',
    module: 'SEO',
    title: 'duplicate URL',
    category: 'technical',
    targetKind: 'site',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'distinct crawled URLs collapse to one normalized URL (duplicates inside scope)',
  },
  {
    ruleId: 'SEO-TECH-008',
    module: 'SEO',
    title: 'index/noindex',
    category: 'technical',
    targetKind: 'page',
    severity: 'High',
    scoring: 'scored',
    oracle: 'meta robots or X-Robots-Tag marks an in-scope indexable page as noindex',
  },
  {
    ruleId: 'SEO-TECH-013',
    module: 'SEO',
    title: 'HTTPS/mixed content',
    category: 'technical',
    targetKind: 'page',
    severity: 'High',
    scoring: 'scored',
    oracle: 'page served over plain HTTP or an https page references http:// subresources',
  },
];

const SEO_ONPAGE_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'SEO-ONPAGE-001',
    module: 'SEO',
    title: 'title',
    category: 'on-page',
    targetKind: 'page',
    severity: 'High',
    scoring: 'scored',
    oracle: 'document head lacks exactly one non-empty <title>',
  },
  {
    ruleId: 'SEO-ONPAGE-002',
    module: 'SEO',
    title: 'meta description',
    category: 'on-page',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'non-empty meta description missing or duplicated',
  },
  {
    ruleId: 'SEO-ONPAGE-003',
    module: 'SEO',
    title: 'H1-H6 structure',
    category: 'on-page',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'H1 missing/duplicated or heading levels skip in the DOM outline',
  },
  {
    ruleId: 'SEO-ONPAGE-005',
    module: 'SEO',
    title: 'image alt',
    category: 'on-page',
    targetKind: 'page',
    severity: 'Low',
    scoring: 'scored',
    oracle: 'content <img> elements without an alt attribute',
  },
];

// GEO rules are informational in v0.1: the module is assessed via readiness practices
// on mock provider responses without score penalties (score_delta = 0, §15/GEO-METHOD-005).
const GEO_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'GEO-PROVIDER-001',
    module: 'AI SEO / GEO',
    title: 'provider adapter contract',
    category: 'provider-adapter',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'provider response normalizes into the §5 contract (all fields, total = input + output)',
  },
  {
    ruleId: 'GEO-VIS-003',
    module: 'AI SEO / GEO',
    title: 'brand presence',
    category: 'visibility',
    targetKind: 'site',
    severity: null,
    scoring: 'informational',
    oracle: 'normalized AI response text mentions the brand name',
  },
  {
    ruleId: 'GEO-VIS-004',
    module: 'AI SEO / GEO',
    title: 'site link',
    category: 'visibility',
    targetKind: 'site',
    severity: null,
    scoring: 'informational',
    oracle: 'normalized AI response contains a link to the site domain',
  },
  {
    ruleId: 'GEO-METHOD-002',
    module: 'AI SEO / GEO',
    title: 'metadata capture',
    category: 'methodology',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle: 'provider/model/prompt/region/language/date/source metadata captured per AI response',
  },
  {
    ruleId: 'GEO-METHOD-005',
    module: 'AI SEO / GEO',
    title: 'unavailable semantics',
    category: 'methodology',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'unavailable provider/query yields module Unavailable without penalty or ai_response record',
  },
];

const SECURITY_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'SEC-PASSIVE-002',
    module: 'Security',
    title: 'security headers',
    category: 'passive',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle:
      'baseline security headers absent from the response (nosniff, frame protection, referrer policy)',
  },
  {
    ruleId: 'SEC-PASSIVE-003',
    module: 'Security',
    title: 'HSTS',
    category: 'passive',
    targetKind: 'site',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'Strict-Transport-Security missing or with insufficient max-age on https responses',
  },
  {
    ruleId: 'SEC-PASSIVE-005',
    module: 'Security',
    title: 'cookie attributes',
    category: 'passive',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'Set-Cookie without Secure, HttpOnly, or SameSite attributes',
  },
];

const RELIABILITY_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'REL-URL-001',
    module: 'Reliability',
    title: 'URL availability',
    category: 'url',
    targetKind: 'page',
    severity: 'High',
    scoring: 'scored',
    oracle:
      'URL fails to resolve or respond within limits (10 s per attempt, 40 s chain deadline, D-023)',
  },
  {
    ruleId: 'REL-URL-003',
    module: 'Reliability',
    title: '4xx/5xx verdict',
    category: 'url',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'unexpected 4xx/5xx yields warning/fail; expected status passes with §9 precedence',
  },
  {
    ruleId: 'REL-URL-009',
    module: 'Reliability',
    title: 'response time',
    category: 'url',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'response time exceeds the reliability threshold',
  },
  {
    ruleId: 'REL-API-003',
    module: 'Reliability',
    title: 'expected status',
    category: 'api',
    targetKind: 'api',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'response status differs from the explicitly expected one; expected 3xx/404/5xx passes',
  },
  {
    ruleId: 'REL-API-005',
    module: 'Reliability',
    title: 'no-credentials policy',
    category: 'api',
    targetKind: 'api',
    severity: 'High',
    scoring: 'scored',
    oracle:
      'API check configured with credentials, request body, or state-changing method is blocked',
  },
];

const ACCESSIBILITY_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'A11Y-002',
    module: 'Accessibility',
    title: 'alt text',
    category: 'dom',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'meaningful images without non-empty alt text in the DOM',
  },
  {
    ruleId: 'A11Y-004',
    module: 'Accessibility',
    title: 'form labels',
    category: 'dom',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle:
      'form control lacks an associated label (label[for], wrapping label, aria-label/labelledby)',
  },
];

const CONTENT_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'CONTENT-003',
    module: 'Content Quality',
    title: 'empty/low-value content',
    category: 'quality',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'visible text below 200 characters marks the page empty/low-value (boundary at 200)',
  },
  {
    ruleId: 'CONTENT-004',
    module: 'Content Quality',
    title: 'broken media',
    category: 'quality',
    targetKind: 'page',
    severity: 'Medium',
    scoring: 'scored',
    oracle: 'referenced images/media respond non-2xx or with a non-media content type',
  },
];

const PRIVACY_RULES: readonly RuleDescriptor[] = [
  {
    ruleId: 'PRIVACY-001',
    module: 'Privacy',
    title: 'cookies',
    category: 'data-collection',
    targetKind: 'page',
    severity: 'Low',
    scoring: 'scored',
    oracle: 'cookies observed via Set-Cookie/document markup are inventoried and reported',
  },
  {
    ruleId: 'PRIVACY-003',
    module: 'Privacy',
    title: 'third-party scripts',
    category: 'data-collection',
    targetKind: 'page',
    severity: 'Low',
    scoring: 'scored',
    oracle: 'third-party script origins referenced by the page are inventoried and reported',
  },
];

/** Scanner + GEO rules of rules-mvp-0.1 (platform contracts live separately). */
export const RULES_MVP_01: readonly RuleDescriptor[] = [
  ...SEO_TECHNICAL_RULES,
  ...SEO_ONPAGE_RULES,
  ...GEO_RULES,
  ...SECURITY_RULES,
  ...RELIABILITY_RULES,
  ...ACCESSIBILITY_RULES,
  ...CONTENT_RULES,
  ...PRIVACY_RULES,
];
