import type { RuleDescriptor } from './ruleset-types.js';

// Platform contracts are test invariants over billing/export/economics behaviour,
// not scanner rules: they never run against a target site and never score.
export const PLATFORM_CONTRACTS: readonly RuleDescriptor[] = [
  {
    ruleId: 'BILLING-001',
    module: 'platform',
    title: 'webhook signature/amount/currency/price validation',
    category: 'billing',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'webhook with invalid HMAC signature or mismatched amount/currency/price ID is rejected',
  },
  {
    ruleId: 'BILLING-002',
    module: 'platform',
    title: 'webhook deduplication',
    category: 'billing',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'duplicate (provider, provider_event_id) produces no second side effect (unique dedup constraint)',
  },
  {
    ruleId: 'BILLING-003',
    module: 'platform',
    title: 'purchase-entitlement-scan uniqueness',
    category: 'billing',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle: 'one purchase yields exactly one entitlement and one scan (unique purchase_id)',
  },
  {
    ruleId: 'BILLING-004',
    module: 'platform',
    title: 'atomic worker claim and retry counters',
    category: 'billing',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'exactly one worker wins the claim; platform_retry_count <= 1 and module_retry_count <= 1',
  },
  {
    ruleId: 'BILLING-005',
    module: 'platform',
    title: 'cancel/refund state machine',
    category: 'billing',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'only §18 state machine transitions are accepted; out-of-order events never roll back state',
  },
  {
    ruleId: 'BILLING-006',
    module: 'platform',
    title: 'NoUsableOutput and platform retry',
    category: 'billing',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'zero usable output after the allowed retry yields Failed/NoUsableOutput and a full refund',
  },
  {
    ruleId: 'EXPORT-001',
    module: 'platform',
    title: 'JSON Schema and semantic validator',
    category: 'export',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle: 'every export record passes schema v1 plus the cross-field semantic invariants',
  },
  {
    ruleId: 'EXPORT-002',
    module: 'platform',
    title: 'canonical record equality across views',
    category: 'export',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle: 'JSON and CSV views are built from the identical canonical record set',
  },
  {
    ruleId: 'EXPORT-003',
    module: 'platform',
    title: 'CSV encoding/order/quoting/nulls',
    category: 'export',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle: 'UTF-8 without BOM, LF, RFC 4180 quoting, fixed header/order, null as empty field',
  },
  {
    ruleId: 'ECON-001',
    module: 'platform',
    title: 'economics forecast validation',
    category: 'economics',
    targetKind: 'environment',
    severity: null,
    scoring: 'informational',
    oracle:
      'forecast passes cost ceilings, support-reserve floor, operational floor 45, break-even',
  },
];
